### ISSUE TITLE
package.jsonがないのは意図的なものか？

### ISSUE THREAD

**Issue by Aomeee** [whiteflare/Unlit_WF_ShaderSuite#3]
URP(2021)環境での利用を検討していたのですが、UPM経由でのインストールの際package.jsonがなくインストールが少々手間だなと感じた部分がありました。これは意図的なものでしょうか？

**Comment by whiteflare** [comment]
URP(2021)版はユーザが少ないことから、現状ではパッケージングは行っておらずgitから直接アセットをダウンロードしていただく形とさせていただいております。
ユーザが増える見込みがある場合は改めてお問い合わせいただければパッケージング化をさせていただきます。
